defaultLanguage: english

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: "*"
